env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:import/recommended
plugins:
  - import
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
    - never
  array-bracket-spacing:
    - error
    - never
  arrow-parens:
    - error
    - as-needed
  block-spacing:
    - error
    - always
  prefer-const: error
  # Import rules
  import/no-unresolved:
    - error
    - commonjs: true
  import/no-named-as-default-member: off
  import/newline-after-import: error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - [parent, sibling]
        - index
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
